//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFARTHA.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AMOR_ANT
    {
        public int POS { get; set; }
        public decimal NUM_DOC { get; set; }
        public string EBELN { get; set; }
        public string EBELP { get; set; }
        public string BELNR { get; set; }
        public Nullable<decimal> GJAHR { get; set; }
        public Nullable<decimal> BUZEI { get; set; }
        public Nullable<decimal> ANTAMOR { get; set; }
        public Nullable<decimal> TANT { get; set; }
        public string WAERS { get; set; }
        public Nullable<decimal> ANTTRANS { get; set; }
        public Nullable<decimal> ANTXAMORT { get; set; }
    
        public virtual DOCUMENTO DOCUMENTO { get; set; }
        public virtual EKPO EKPO { get; set; }
    }
}
