//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFARTHA.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CECO
    {
        public string BUKRS { get; set; }
        public string CECO1 { get; set; }
        public string TEXT { get; set; }
        public bool ACTIVO { get; set; }
    }
}
