//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFARTHA.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLAVES_CONTA
    {
        public string TSOL { get; set; }
        public string DH { get; set; }
        public string BSCHL { get; set; }
        public string BSCHLL { get; set; }
    }
}
