//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFARTHA.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONCEPTO
    {
        public string ID_CONCEPTO { get; set; }
        public string DESC_CONCEPTO { get; set; }
        public string TIPO_CONCEPTO { get; set; }
        public string TIPO_IMPUTACION { get; set; }
        public string ID_PRESUPUESTO { get; set; }
        public string TIPO_PRESUPUESTO { get; set; }
        public string CUENTA { get; set; }
        public bool ACTIVO { get; set; }
    }
}
