//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFARTHA.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONMAIL
    {
        public string ID { get; set; }
        public string HOST { get; set; }
        public Nullable<int> PORT { get; set; }
        public bool SSL { get; set; }
        public string MAIL { get; set; }
        public string PASS { get; set; }
        public bool ACTIVO { get; set; }
    }
}
