//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFARTHA.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DET_AGENTEC
    {
        public string USUARIOC_ID { get; set; }
        public int VERSION { get; set; }
        public int POS { get; set; }
        public string USUARIOA_ID { get; set; }
        public Nullable<decimal> MONTO { get; set; }
        public bool PRESUPUESTO { get; set; }
        public bool MAIL { get; set; }
        public bool ACTIVO { get; set; }
    
        public virtual USUARIO USUARIO { get; set; }
        public virtual USUARIO USUARIO1 { get; set; }
    }
}
