//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFARTHA.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DET_PROYECTO_DEC_V
    {
        public string ID_PSPNR { get; set; }
        public string NOMBRE { get; set; }
        public string ID_BUKRS { get; set; }
        public string BUTXT { get; set; }
    }
}
