//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFARTHA.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DET_TIPOPRESUPUESTO
    {
        public string BUKRS { get; set; }
        public string ID_USER { get; set; }
        public string TIPOPRE { get; set; }
    
        public virtual SOCIEDAD SOCIEDAD { get; set; }
        public virtual TIPOPRESUPUESTO TIPOPRESUPUESTO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
