//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFARTHA.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DET_AGENTECA
    {
        public string ID_RUTA_AGENTE { get; set; }
        public int VERSION { get; set; }
        public int STEP_FASE { get; set; }
        public int STEP_ACCION { get; set; }
        public decimal LIM_SUP { get; set; }
        public string AGENTE_SIG { get; set; }
        public Nullable<bool> OVERRIDE { get; set; }
    }
}
