//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFARTHA.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DET_PROYECTO_DEC_V
    {
        public string ID_PSPNR { get; set; }
        public string NOMBRE { get; set; }
        public string ID_BUKRS { get; set; }
        public string BUTXT { get; set; }
    }
}
