//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFARTHA.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DET_AGENTECC
    {
        public int VERSION { get; set; }
        public string USUARIOC_ID { get; set; }
        public string ID_RUTA_AGENTE { get; set; }
        public string DESCRIPCION { get; set; }
        public string USUARIOA_ID { get; set; }
        public System.DateTime FECHAC { get; set; }
    }
}
