//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFARTHA.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DET_PEP
    {
        public string PSPNR { get; set; }
        public Nullable<int> POSID { get; set; }
        public string DESCRIPCION { get; set; }
        public string CONCEPTO { get; set; }
        public string TIPO_CONCEPTO { get; set; }
    }
}
