//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFARTHA.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DET_AGENTECA
    {
        public string ID_RUTA_AGENTE { get; set; }
        public int VERSION { get; set; }
        public int STEP_FASE { get; set; }
        public int STEP_ACCION { get; set; }
        public decimal LIM_SUP { get; set; }
        public string AGENTE_SIG { get; set; }
        public Nullable<bool> OVERRIDE { get; set; }
    }
}
