//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFARTHA.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DET_PEP
    {
        public string PSPNR { get; set; }
        public Nullable<int> POSID { get; set; }
        public string DESCRIPCION { get; set; }
        public string CONCEPTO { get; set; }
        public string TIPO_CONCEPTO { get; set; }
    }
}
