//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFARTHA.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DET_AGENTECC
    {
        public int VERSION { get; set; }
        public string USUARIOC_ID { get; set; }
        public string ID_RUTA_AGENTE { get; set; }
        public string DESCRIPCION { get; set; }
        public string USUARIOA_ID { get; set; }
        public System.DateTime FECHAC { get; set; }
    }
}
