//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFARTHA.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DET_AGENTEC
    {
        public string USUARIOC_ID { get; set; }
        public int VERSION { get; set; }
        public int POS { get; set; }
        public string USUARIOA_ID { get; set; }
        public Nullable<decimal> MONTO { get; set; }
        public bool PRESUPUESTO { get; set; }
        public bool MAIL { get; set; }
        public bool ACTIVO { get; set; }
    
        public virtual USUARIO USUARIO { get; set; }
        public virtual USUARIO USUARIO1 { get; set; }
    }
}
