//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFARTHA.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DET_TIPODOC
    {
        public string TIPO_SOL { get; set; }
        public string BLART { get; set; }
    
        public virtual TSOL TSOL { get; set; }
    }
}
