//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFARTHA.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DET_APROB
    {
        public int VERSION { get; set; }
        public string ID_SOCIEDAD { get; set; }
        public string ID_USUARIO { get; set; }
        public int STEP_FASE { get; set; }
    }
}
