//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFARTHA.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCUMENTOPRE
    {
        public decimal NUM_DOC { get; set; }
        public decimal POS { get; set; }
        public string MESSAGE { get; set; }
    
        public virtual DOCUMENTO DOCUMENTO { get; set; }
    }
}
