//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFARTHA.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCUMENTOR
    {
        public decimal NUM_DOC { get; set; }
        public string WITHT { get; set; }
        public string WT_WITHCD { get; set; }
        public Nullable<decimal> POS { get; set; }
        public Nullable<decimal> BIMPONIBLE { get; set; }
        public Nullable<decimal> IMPORTE_RET { get; set; }
        public Nullable<bool> VISIBLE { get; set; }
    
        public virtual DOCUMENTO DOCUMENTO { get; set; }
    }
}
