//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFARTHA.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCUMENTOCOC
    {
        public decimal NUM_DOC { get; set; }
        public decimal POSD { get; set; }
        public Nullable<int> POS { get; set; }
        public string MATNR { get; set; }
        public string PS_PSP_PNR { get; set; }
        public string WAERS { get; set; }
        public Nullable<decimal> MENGE_BIL { get; set; }
        public string MEINS { get; set; }
    
        public virtual DOCUMENTOP DOCUMENTOP { get; set; }
    }
}
