//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFARTHA.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCUMENTOPRE
    {
        public decimal NUM_DOC { get; set; }
        public decimal POS { get; set; }
        public string MESSAGE { get; set; }
    
        public virtual DOCUMENTO DOCUMENTO { get; set; }
    }
}
