//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFARTHA.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCUMENTOA1
    {
        public decimal NUM_DOC { get; set; }
        public int POS { get; set; }
        public string TIPO { get; set; }
        public string DESC { get; set; }
        public string CLASE { get; set; }
        public Nullable<int> STEP_WF { get; set; }
        public string USUARIO_ID { get; set; }
        public string PATH { get; set; }
        public Nullable<bool> ACTIVO { get; set; }
    
        public virtual DOCUMENTO DOCUMENTO { get; set; }
    }
}
