//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFARTHA.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCUMENTOCOC
    {
        public decimal NUM_DOC { get; set; }
        public decimal POSD { get; set; }
        public Nullable<int> POS { get; set; }
        public string MATNR { get; set; }
        public string PS_PSP_PNR { get; set; }
        public string WAERS { get; set; }
        public Nullable<decimal> MENGE_BIL { get; set; }
        public string MEINS { get; set; }
    
        public virtual DOCUMENTOP DOCUMENTOP { get; set; }
    }
}
