//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFARTHA.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCUMENTOA
    {
        public decimal NUM_DOC { get; set; }
        public decimal POSD { get; set; }
        public int POS { get; set; }
        public string TIPO { get; set; }
        public string DESC { get; set; }
        public string CLASE { get; set; }
        public Nullable<int> STEP_WF { get; set; }
        public string USUARIO_ID { get; set; }
        public string PATH { get; set; }
        public bool ACTIVO { get; set; }
    
        public virtual DOCUMENTOP DOCUMENTOP { get; set; }
        public virtual TSOPORTE TSOPORTE { get; set; }
    }
}
