//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFARTHA.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class EKBE
    {
        public string EBELN { get; set; }
        public string EBELP { get; set; }
        public decimal ZEKKN { get; set; }
        public string VGABE { get; set; }
        public decimal GJAHR { get; set; }
        public string BELNR { get; set; }
        public decimal BUZEI { get; set; }
        public string BEWTP { get; set; }
        public string WAERS { get; set; }
        public Nullable<decimal> DMBTR { get; set; }
        public Nullable<decimal> WRBTR { get; set; }
        public string SHKZG { get; set; }
        public Nullable<System.DateTime> BUDAT { get; set; }
        public string XBLNR { get; set; }
        public string REBZG { get; set; }
        public string REBZJ { get; set; }
        public Nullable<decimal> REBZZ { get; set; }
        public string XREVERSED { get; set; }
        public string XREVERSEING { get; set; }
        public string STJAAH { get; set; }
        public string STBLG { get; set; }
        public Nullable<System.DateTime> AUDT { get; set; }
        public string AUGBL { get; set; }
    }
}
