//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFARTHA.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class EKBE_DUMMY
    {
        public string EBELN { get; set; }
        public decimal EBELP { get; set; }
        public decimal ZEKKN { get; set; }
        public string VGABE { get; set; }
        public decimal GJAHR { get; set; }
        public string BELNR { get; set; }
        public decimal BUZEI { get; set; }
        public string BEWTP { get; set; }
        public string WAERS { get; set; }
        public Nullable<decimal> DMBTR { get; set; }
        public Nullable<decimal> WRBTR { get; set; }
        public Nullable<System.DateTime> BUDAT { get; set; }
        public string XBLNR { get; set; }
    }
}
