//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFARTHA.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class EKBE_DUMMY
    {
        public string EBELN { get; set; }
        public decimal EBELP { get; set; }
        public decimal ZEKKN { get; set; }
        public string VGABE { get; set; }
        public decimal GJAHR { get; set; }
        public string BELNR { get; set; }
        public decimal BUZEI { get; set; }
        public string BEWTP { get; set; }
        public string WAERS { get; set; }
        public Nullable<decimal> DMBTR { get; set; }
        public Nullable<decimal> WRBTR { get; set; }
        public Nullable<System.DateTime> BUDAT { get; set; }
        public string XBLNR { get; set; }
    }
}
