//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFARTHA.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class EKKO
    {
        public string EBELN { get; set; }
        public string BUKRS { get; set; }
        public string BSART { get; set; }
        public string LIFNR { get; set; }
        public string RETTP { get; set; }
        public Nullable<decimal> RETPC { get; set; }
        public string DPTYP { get; set; }
        public Nullable<decimal> DPPCT { get; set; }
        public Nullable<decimal> DPAMT { get; set; }
        public string ESTATUS { get; set; }
    }
}
