//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFARTHA.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class EKPO_DUMMY
    {
        public string EBELN { get; set; }
        public decimal EBELP { get; set; }
        public Nullable<System.DateTime> BEDAT { get; set; }
        public string MATNR { get; set; }
        public string TXZ01 { get; set; }
        public string MATKL { get; set; }
        public string WERKS { get; set; }
        public string LGORT { get; set; }
        public Nullable<decimal> MENGE { get; set; }
        public string MEINS { get; set; }
        public Nullable<decimal> NETPR { get; set; }
        public string WAERS { get; set; }
        public Nullable<decimal> PEINH { get; set; }
        public Nullable<decimal> MENGE_DEL { get; set; }
        public Nullable<decimal> NETPR_DEL { get; set; }
        public Nullable<decimal> MENGE_BIL { get; set; }
        public Nullable<decimal> NETPR_BIL { get; set; }
        public string MWSKZ { get; set; }
    }
}
