//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFARTHA.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESTATUS_PAGO
    {
        public string BELNR { get; set; }
        public string GJAHR { get; set; }
        public string BUKRS { get; set; }
        public string BELNR_P { get; set; }
        public string GJAHR_P { get; set; }
        public string BUKRS_P { get; set; }
        public string BUZEI { get; set; }
        public string LIFNR { get; set; }
        public string TIPO { get; set; }
        public string BLDAT_P { get; set; }
        public Nullable<decimal> WRBTR_P { get; set; }
        public string WAERS { get; set; }
    }
}
