//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFARTHA.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESTATUS_PAGO
    {
        public string BELNR { get; set; }
        public string GJAHR { get; set; }
        public string BUKRS { get; set; }
        public string BELNR_P { get; set; }
        public string GJAHR_P { get; set; }
        public string BUKRS_P { get; set; }
        public string BUZEI { get; set; }
        public string LIFNR { get; set; }
        public string TIPO { get; set; }
        public string BLDAT_P { get; set; }
        public Nullable<decimal> WRBTR_P { get; set; }
        public string WAERS { get; set; }
    }
}
