//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFARTHA.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLUJO
    {
        public string WORKF_ID { get; set; }
        public int WF_VERSION { get; set; }
        public int WF_POS { get; set; }
        public decimal NUM_DOC { get; set; }
        public int POS { get; set; }
        public int DETPOS { get; set; }
        public Nullable<int> DETVER { get; set; }
        public Nullable<int> LOOP { get; set; }
        public string USUARIOA_ID { get; set; }
        public string USUARIOD_ID { get; set; }
        public string ESTATUS { get; set; }
        public Nullable<System.DateTime> FECHAC { get; set; }
        public Nullable<System.DateTime> FECHAM { get; set; }
        public string COMENTARIO { get; set; }
        public string ID_RUTA_A { get; set; }
        public Nullable<int> RUTA_VERSION { get; set; }
        public Nullable<int> STEP_AUTO { get; set; }
        public int VERSIONC1 { get; set; }
        public int VERSIONC2 { get; set; }
        public Nullable<System.DateTime> FECHACON { get; set; }
    
        public virtual DOCUMENTO DOCUMENTO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        public virtual USUARIO USUARIO1 { get; set; }
        public virtual WORKFP WORKFP { get; set; }
    }
}
