//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFARTHA.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FORMATO
    {
        public int ID { get; set; }
        public string MILES { get; set; }
        public string DECIMALES { get; set; }
        public bool ACTIVO { get; set; }
    }
}
