//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFARTHA.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FORO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FORO()
        {
            this.FORODs = new HashSet<FOROD>();
        }
    
        public byte ID_FORO { get; set; }
        public string ID_USUARIO { get; set; }
        public decimal NUM_DOC { get; set; }
        public string TITULO { get; set; }
        public System.DateTime CREADO { get; set; }
        public Nullable<System.DateTime> CERRADO { get; set; }
        public Nullable<bool> MAIL { get; set; }
    
        public virtual DOCUMENTO DOCUMENTO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FOROD> FORODs { get; set; }
    }
}
