//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFARTHA.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERMISO_PAGINA
    {
        public int PAGINA_ID { get; set; }
        public int ROL_ID { get; set; }
        public Nullable<bool> PERMISO { get; set; }
    
        public virtual PAGINA PAGINA { get; set; }
    }
}
