//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFARTHA.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERMISO_PAGINA
    {
        public int PAGINA_ID { get; set; }
        public int ROL_ID { get; set; }
        public Nullable<bool> PERMISO { get; set; }
    
        public virtual PAGINA PAGINA { get; set; }
    }
}
