//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFARTHA.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RETENCION_PROV
    {
        public string LIFNR { get; set; }
        public string BUKRS { get; set; }
        public string WITHT { get; set; }
        public string WT_WITHCD { get; set; }
    
        public virtual PROVEEDOR PROVEEDOR { get; set; }
        public virtual RETENCION RETENCION { get; set; }
        public virtual SOCIEDAD SOCIEDAD { get; set; }
    }
}
