//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFARTHA.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RETENCION_PROV
    {
        public string LIFNR { get; set; }
        public string BUKRS { get; set; }
        public string WITHT { get; set; }
        public string WT_WITHCD { get; set; }
    
        public virtual PROVEEDOR PROVEEDOR { get; set; }
        public virtual RETENCION RETENCION { get; set; }
        public virtual SOCIEDAD SOCIEDAD { get; set; }
    }
}
