//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFARTHA.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPOPRESUPUESTOT
    {
        public string SPRAS_ID { get; set; }
        public string TIPOPRE { get; set; }
        public string TEXT30 { get; set; }
    
        public virtual SPRA SPRA { get; set; }
        public virtual TIPOPRESUPUESTO TIPOPRESUPUESTO { get; set; }
    }
}
