//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFARTHA.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSOL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TSOL()
        {
            this.DOCUMENTOes = new HashSet<DOCUMENTO>();
            this.TSOLTs = new HashSet<TSOLT>();
            this.WORKFHs = new HashSet<WORKFH>();
        }
    
        public string ID { get; set; }
        public string DESCRIPCION { get; set; }
        public string RANGO_ID { get; set; }
        public string ESTATUS { get; set; }
        public Nullable<bool> EDITDET { get; set; }
        public Nullable<bool> DEFAULT { get; set; }
        public string TIPO_DOCFILE { get; set; }
        public bool ACTIVO { get; set; }
    
        public virtual DET_TIPODOC DET_TIPODOC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DOCUMENTO> DOCUMENTOes { get; set; }
        public virtual RANGO RANGO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSOLT> TSOLTs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WORKFH> WORKFHs { get; set; }
    }
}
