//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFARTHA.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class WARNINGV
    {
        public int PAGINA_ID { get; set; }
        public string ID { get; set; }
        public string DESCRIPCION { get; set; }
        public string TIPO { get; set; }
        public string SPRAS_ID { get; set; }
        public string WARNING { get; set; }
        public string POSICION { get; set; }
        public Nullable<bool> ACTIVO { get; set; }
    }
}
