//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFARTHA.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class WARNINGV
    {
        public int PAGINA_ID { get; set; }
        public string ID { get; set; }
        public string DESCRIPCION { get; set; }
        public string TIPO { get; set; }
        public string SPRAS_ID { get; set; }
        public string WARNING { get; set; }
        public string POSICION { get; set; }
        public Nullable<bool> ACTIVO { get; set; }
    }
}
