//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFARTHA.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class WORKFP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WORKFP()
        {
            this.FLUJOes = new HashSet<FLUJO>();
        }
    
        public string ID { get; set; }
        public int VERSION { get; set; }
        public int POS { get; set; }
        public Nullable<int> AGENTE_ID { get; set; }
        public Nullable<int> ACCION_ID { get; set; }
        public Nullable<int> NEXT_STEP { get; set; }
        public Nullable<int> NS_ACCEPT { get; set; }
        public Nullable<int> NS_REJECT { get; set; }
        public Nullable<int> LOOPS { get; set; }
        public Nullable<int> CONDICION_ID { get; set; }
        public Nullable<int> NS_CN_ACCEPT { get; set; }
        public Nullable<int> NS_CN_REJECT { get; set; }
        public string EMAIL { get; set; }
        public Nullable<int> EMAIL_TXT_ID { get; set; }
        public Nullable<int> EMAIL_INN_ID { get; set; }
    
        public virtual ACCION ACCION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FLUJO> FLUJOes { get; set; }
        public virtual WORKFV WORKFV { get; set; }
    }
}
